//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TidUpWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCOMPANY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCOMPANY()
        {
            this.TBLFOLDER = new HashSet<TBLFOLDER>();
            this.TBLUSER = new HashSet<TBLUSER>();
        }
    
        public int COMPANYID { get; set; }
        public string COMPANYCODE { get; set; }
        public string COMPANYNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFOLDER> TBLFOLDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUSER> TBLUSER { get; set; }
    }
}
