//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TidUpWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFOLDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLFOLDER()
        {
            this.TBLPRODUCT = new HashSet<TBLPRODUCT>();
            this.TBLLOGS = new HashSet<TBLLOGS>();
        }
    
        public int FOLDERID { get; set; }
        public string FOLDERNAME { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TBLCOMPANY TBLCOMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPRODUCT> TBLPRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLLOGS> TBLLOGS { get; set; }
    }
}
