//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TidUpWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOGS
    {
        public int ID { get; set; }
        public string ACTION { get; set; }
        public string CONTROLLER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string INFO { get; set; }
        public string USERNAME { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<int> FOLDERID { get; set; }
        public Nullable<int> PRODUCTID { get; set; }
    
        public virtual TBLPRODUCT TBLPRODUCT { get; set; }
        public virtual TBLFOLDER TBLFOLDER { get; set; }
    }
}
