//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TidUpWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPRODUCT()
        {
            this.TBLLOGS = new HashSet<TBLLOGS>();
        }
    
        public int PRODUCTID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> BARCODE { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> FOLDERID { get; set; }
        public string PHOTO { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual TBLFOLDER TBLFOLDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLLOGS> TBLLOGS { get; set; }
    }
}
